sudo: false
language: ruby
rvm:
  - 2.2.2

cache:
  - bundler

addons:
  postgresql: 9.3

services:
  - redis
  - postgresql

before_script:
  - 'cp config/database.yml.example config/database.yml'
  - 'cp config/travis.yml.example config/travis.yml'
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load db:migrate --trace'

script:
  - bundle exec rspec
